### ISSUE TITLE
Unable to force pawns to equip clothing via right-click

### ISSUE THREAD

**Issue by Weblure** [Chennex/Avali-Continued#1]
No menu appears at all when right-clicking clothing while a pawn is selected. My only active mods are this, base royalty, and Humanoid Alien Races 2.

**Comment by Chennex** [comment]
Hello, sorry for the late reply. This should be fixed. Let me know if the issue persists.

**Comment by Weblure** [comment]
Thanks for coming back to this! I'll test it out when I get the chance
